version: '3.3'
services:
  app:
    image: 'appimage:1'
    depends_on:
      - redis
    ports:
      - 8080:8080
    networks:
      - monreseau
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - monreseau

networks:
  monreseau:
    driver: bridge

